### PR TITLE
Replace hardcoded browser list with xdg-open

### PR DESCRIPTION
**Pull request by ghost**
#61 continued

### CODE REVIEW

**Comment by varmd** [comment]
PR would break the use-case when user has no default browsers from xdg-open or xdg-open is not configured. So the PR should first run xdg-open, check the return code and run open_url if not successfull.

**Comment by milkknife** [comment]
> So the PR should first run xdg-open, check the return code and run open_url if not successfull.

That's what it does

**Comment by varmd** [comment]
No, it just checks for existence of xdg-open. It needs to run xdg-open and check the return code `$?`

**Comment by milkknife** [comment]
Sorry, I misunderstood. How about now?

**Pull request closed without merging**
